import { Container, Graphics, Text, TextStyle } from 'pixi.js';
import { GAME_WIDTH, FONT_FAMILY, COLORS } from '@/app/constants';
import { TEXT_RESOLUTION } from '@/ui/typography/text-styles';

const CHYRON_Y = 655;
const CHYRON_H = 55;
const BADGE_W = 200;
const HEADLINE_AREA_W = GAME_WIDTH - BADGE_W;
const SCROLL_SPEED = 60;
const SLIDE_DURATION = 0.4;

const VICTORY_HEADLINES = [
  'OIL PRICES PLUMMET AS STRAIT OF HORMUZ REMAINS OPEN FOR BUSINESS',
  'GAS STATION OWNERS IN DISBELIEF AS PRICES DROP BELOW $2/GALLON',
  'ECONOMISTS STUNNED: "WE DIDN\'T THINK PRICES COULD ACTUALLY GO DOWN"',
  'SUBURBAN DAD FILLS SUV FOR $30, CALLS IT "BEST DAY OF MY LIFE"',
  'OPEC EMERGENCY MEETING CALLED: "WHO AUTHORIZED THE NAVY?"',
  'TESLA STOCK DIPS AS GASOLINE BECOMES CHEAPER THAN CHARGING',
  'NATIONS WORLDWIDE DECLARE NATIONAL HOLIDAY AS HEATING BILLS PLUMMET',
  'AVOCADO TOAST NOW OFFICIALLY MORE EXPENSIVE THAN A GALLON OF GAS',
  'AIRLINE TICKETS DROP 40% — SPIRIT AIRLINES NOW LITERALLY PAYS YOU TO FLY',
  'UBER DRIVERS REPORT RECORD PROFITS AS FUEL COSTS EVAPORATE',
  'WORLD BANK UPGRADES GLOBAL OUTLOOK TO "ACTUALLY PRETTY GREAT"',
  'MAN DRIVES HUMMER GUILT-FREE FOR FIRST TIME SINCE 2004',
  'SHIPPING COMPANIES REPORT RECORD PROFITS — "THANK THE NAVY" SAYS CEO',
  'CRYPTO BROS PIVOT BACK TO OIL FUTURES: "THIS ONE ACTUALLY MAKES SENSE"',
  'LOCAL MOM FILLS MINIVAN — STILL HAS MONEY LEFT FOR GROCERIES',
  'DOW SURGES 2,000 POINTS ON NEWS OF SUCCESSFUL CONVOY ESCORT',
  'PRICE OF EVERYTHING DROPS AS SUPPLY CHAINS BREATHE SIGH OF RELIEF',
  'TRUCKING INDUSTRY CELEBRATES: "WE CAN ACTUALLY DELIVER THINGS AGAIN"',
  'PIZZA DELIVERY FEES DROP FOR FIRST TIME IN RECORDED HISTORY',
  'AMAZON CUTS PRIME MEMBERSHIP PRICE CITING LOWER SHIPPING COSTS',
  'FARMERS REJOICE AS DIESEL PRICES RETURN TO EARTH — FOOD COSTS TO FOLLOW',
  'NAVY ESCORT COMMANDER OFFERED KEY TO EVERY CITY SIMULTANEOUSLY',
  'PENTAGON BRIEFING JUST A GUY SMILING AND POINTING AT A CHART GOING DOWN',
  'INTERNATIONAL SHIPPING RATES NOSEDIVE — YOUR ALIEXPRESS ORDER MAY ACTUALLY ARRIVE',
  'ROAD TRIP SEASON DECLARED "BACK ON" BY EVERY DAD IN AMERICA',
  'COSTCO GAS LINE DROPS BELOW 45 MINUTES FOR FIRST TIME SINCE 2019',
  'CONGRESS UNANIMOUSLY AGREES ON SOMETHING FOR FIRST TIME IN DECADES',
  'OIL TRADERS SEEN CALMLY SIPPING COFFEE INSTEAD OF SCREAMING INTO PHONES',
  'HEATING OIL PRICES CRASH — GRANDMA FINALLY TURNS THERMOSTAT ABOVE 62',
  'CARGO SHIPS RESUME NORMAL ROUTES — SUPPLY CHAIN EXPERTS CAUTIOUSLY OPTIMISTIC',
  'CARNIVAL CRUISE STOCK UP 30% — "FUEL IS BASICALLY FREE NOW" SAYS CEO',
  'ECONOMIST ON LIVE TV: "I HAVE NOTHING BAD TO SAY FOR ONCE"',
  'SMALL BUSINESS OWNERS REPORT BEST QUARTER IN YEARS AS COSTS PLUMMET',
  'AAA REPORTS GAS PRICES AT 5-YEAR LOW — RECOMMENDS CELEBRATORY ROAD TRIP',
  'RIDESHARE DRIVERS ACTUALLY MAKING MONEY AGAIN — PASSENGERS STILL TIPPING $0',
  'GLOBAL INFLATION SLOWS AS ENERGY COSTS STABILIZE — FED TAKES VICTORY LAP',
  'MARATHON RUNNER SWITCHES BACK TO DRIVING — "GAS IS JUST CHEAPER NOW"',
  'NAVY RECRUITMENT SURGES 800% AFTER VIRAL STRAIT OF HORMUZ FOOTAGE',
  'WHITE HOUSE CREDITS NAVY: "THESE ARE THE GOOD KIND OF HEADLINES"',
  'JETBLUE ANNOUNCES $29 CROSS-COUNTRY FLIGHTS — "THANK CHEAP FUEL" SAYS SPOKESMAN',
  'LOCAL NEWS: MAN FILLS UP TRUCK AND BOAT ON SAME DAY, NOT BANKRUPT',
  'U.S. STRATEGIC PETROLEUM RESERVE: "HONESTLY WE DIDN\'T EVEN NEED TO TAP IT"',
  'EUROPEAN ALLIES SEND THANK-YOU NOTES AS NATURAL GAS PRICES STABILIZE',
  'FOOD DELIVERY APPS DROP FEES — CUSTOMERS STILL WON\'T TIP',
];

const DEFEAT_HEADLINES = [
  'GLOBAL OIL CRISIS: PRICES SURGE PAST $150 PER BARREL',
  'PENTAGON DENIES REPORTS OF "COMPLETE STRATEGIC CATASTROPHE"',
  'GAS PRICES HIT $9/GALLON — AMERICANS REDISCOVER THE ART OF WALKING',
  'ENTIRE NATION SWITCHES TO BICYCLES OVERNIGHT — SPANDEX SHORTAGE REPORTED',
  'WALL STREET IN FREEFALL AS ENERGY SECTOR DRAGS MARKETS DOWN 15%',
  'AIRLINES CANCEL ALL FLIGHTS — CEO SUGGESTS PASSENGERS "JUST USE ZOOM"',
  'OPEC CELEBRATES WITH SOLID GOLD YACHT CHRISTENING CEREMONY',
  'UBER SURGE PRICING NOW EXCEEDS MONTHLY MORTGAGE PAYMENTS',
  'ECONOMISTS PREDICT RECESSION — "BUT LIKE A COOL VINTAGE ONE" THEY ADD',
  'DADS NATIONWIDE SEEN WEEPING OPENLY AT GAS PUMPS',
  'FLORIDA MAN ATTEMPTS TO REFINE CRUDE OIL IN BACKYARD SWIMMING POOL',
  'ELON MUSK TWEETS "TOLD YOU SO" — TESLA STOCK UP 400% IN ONE DAY',
  'HORSE AND BUGGY SALES SURGE 3,000% ON AMAZON PRIME',
  'LAST GAS STATION IN TOWN CLOSES — MAYOR DECLARES STATE OF EMERGENCY',
  'NATO CONVENES EMERGENCY SESSION — ORDERS 10,000 ELECTRIC SCOOTERS',
  'DOW PLUNGES 3,000 POINTS — TRADERS LAST SEEN HEADING FOR THE EXITS',
  'WORLD LEADERS SEEN ARGUING OVER LAST BARREL OF OIL AT G7 SUMMIT',
  'PIZZA DELIVERY NOW COSTS MORE THAN THE PIZZA ITSELF',
  'COSTCO PARKING LOT FISTFIGHT BREAKS OUT OVER LAST SPOT IN GAS LINE',
  'AMAZON RAISES PRIME MEMBERSHIP TO $300 — BLAMES SHIPPING FUEL COSTS',
  'TRUCKERS REFUSE TO DRIVE — "I\'D LOSE MONEY DELIVERING YOUR STUFF"',
  'HEATING OIL SHORTAGE: VERMONT RESIDENTS BURNING FURNITURE TO STAY WARM',
  'STATE DEPARTMENT ISSUES TRAVEL ADVISORY: "JUST STAY HOME HONESTLY"',
  'FOOD PRICES SPIKE 40% AS TRANSPORTATION COSTS SKYROCKET',
  'COMMUTER TRAINS PACKED TO CAPACITY — CONDUCTORS REPORT "SARDINE CONDITIONS"',
  'USED PRIUS PRICES HIT ALL-TIME HIGH — NOW MORE EXPENSIVE THAN NEW BMW',
  'SILICON VALLEY TECH BROS DISCOVER CARPOOLING — "IT\'S LIKE UBER BUT FREE?"',
  'MAN TRADES PICKUP TRUCK FOR THREE GOATS AND A BICYCLE — CALLS IT "A GOOD DEAL"',
  'THEME PARKS CLOSE AS FAMILIES CAN NO LONGER AFFORD THE DRIVE',
  'CONGRESS HOLDS EMERGENCY HEARING — CANNOT AGREE ON WHAT "EMERGENCY" MEANS',
  'DOORDASH ADDS $15 "FUEL CRISIS SURCHARGE" — CUSTOMERS ORDER ANYWAY',
  'NATIONAL GUARD DEPLOYED TO PROTECT GAS STATIONS FROM PANIC BUYERS',
  'CARGO SHIPS REROUTING AROUND AFRICA — DELIVERY TIMES NOW MEASURED IN MONTHS',
  'THANKSGIVING CANCELED AS FAMILIES UNABLE TO AFFORD TRAVEL HOME',
  'LOCAL WEATHERMAN NOW ALSO REPORTS OIL PRICES — "IT\'S ALL ANYONE ASKS ME ABOUT"',
  'EUROPEAN LEADERS BLAME EACH OTHER IN MOST AWKWARD PRESS CONFERENCE EVER',
  'FARMERS UNABLE TO HARVEST CROPS — "TRACTORS DON\'T RUN ON HOPES AND DREAMS"',
  'SCHOOL DISTRICTS CANCEL BUS SERVICE — PARENTS REDISCOVER WALKING THEIR KIDS',
  'GAS STATION ATTENDANT NOW HIGHEST-PAID PROFESSION IN AMERICA',
  'BLACK MARKET GASOLINE RING BUSTED IN SUBURBAN CUL-DE-SAC',
  'CRUISE INDUSTRY COLLAPSES — SHIPS CONVERTED TO STATIONARY HOTELS',
  'OIL COMPANY CEO TESTIFIES BEFORE CONGRESS WEARING SOLID GOLD WATCH',
  'VPOTUS PHOTOGRAPHED RIDING BICYCLE TO CABINET MEETING',
  'ECONOMISTS NOW JUST SHRUGGING ON LIVE TELEVISION',
];

function pickHeadlines(isVictory: boolean, oilPrice: number): string {
  const pool = isVictory ? [...VICTORY_HEADLINES] : [...DEFEAT_HEADLINES];

  // Add a dynamic headline with the actual oil price
  if (isVictory) {
    pool.push(`CRUDE OIL SETTLES AT $${oilPrice}/BARREL — ANALYSTS CALL IT "A MIRACLE"`);
  } else {
    pool.push(`CRUDE OIL SPIKES TO $${oilPrice}/BARREL — PANIC BUYING REPORTED WORLDWIDE`);
  }

  // Shuffle and pick 4
  for (let i = pool.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  const picked = pool.slice(0, 4);
  return picked.map(h => `  ///  ${h}`).join('');
}

export interface ChyronState {
  container: Container;
  headlineText: Text;
  scrollX: number;
  slideProgress: number;
  isActive: boolean;
}

export function createChyron(isVictory: boolean, oilPrice: number): ChyronState {
  const container = new Container();
  container.y = 720; // starts off-screen, slides up

  // Background
  const bg = new Graphics();
  // Dark red-black fill
  bg.rect(0, 0, GAME_WIDTH, CHYRON_H).fill({ color: 0x1a0000, alpha: 0.95 });
  // Top red accent
  bg.rect(0, 0, GAME_WIDTH, 2).fill({ color: COLORS.red });
  // Bottom red accent
  bg.rect(0, CHYRON_H - 2, GAME_WIDTH, 2).fill({ color: COLORS.red });
  container.addChild(bg);

  // Badge background
  const badge = new Graphics();
  badge.rect(0, 2, BADGE_W, CHYRON_H - 4).fill({ color: 0xcc0000 });
  // Badge right border
  badge.rect(BADGE_W - 2, 2, 2, CHYRON_H - 4).fill({ color: 0xff0000, alpha: 0.8 });
  container.addChild(badge);

  // Badge text
  const badgeText = new Text({
    text: 'BREAKING NEWS',
    style: new TextStyle({
      fontFamily: FONT_FAMILY,
      fontSize: 16,
      fontWeight: 'bold',
      fill: '#ffffff',
      letterSpacing: 2,
    }),
    resolution: TEXT_RESOLUTION,
  });
  badgeText.anchor.set(0.5);
  badgeText.position.set(BADGE_W / 2, CHYRON_H / 2);
  container.addChild(badgeText);

  // Headline text (scrolling)
  const headlineStr = pickHeadlines(isVictory, oilPrice);
  const headlineText = new Text({
    text: headlineStr,
    style: new TextStyle({
      fontFamily: FONT_FAMILY,
      fontSize: 14,
      fontWeight: 'bold',
      fill: isVictory ? '#ffffff' : '#ffaa00',
    }),
    resolution: TEXT_RESOLUTION,
  });
  headlineText.position.set(HEADLINE_AREA_W, CHYRON_H / 2);
  headlineText.anchor.set(0, 0.5);

  // Sub-container for headline with mask
  const headlineContainer = new Container();
  headlineContainer.x = BADGE_W;
  headlineContainer.addChild(headlineText);

  const headlineMask = new Graphics();
  headlineMask.rect(0, 0, HEADLINE_AREA_W, CHYRON_H).fill({ color: 0xffffff });
  headlineContainer.addChild(headlineMask);
  headlineContainer.mask = headlineMask;

  container.addChild(headlineContainer);

  return {
    container,
    headlineText,
    scrollX: HEADLINE_AREA_W,
    slideProgress: 0,
    isActive: false,
  };
}

export function updateChyron(state: ChyronState, dt: number): void {
  // Slide-in animation
  if (state.slideProgress < 1) {
    state.slideProgress = Math.min(1, state.slideProgress + dt / SLIDE_DURATION);
    const t = state.slideProgress;
    const eased = 1 - Math.pow(1 - t, 3); // cubic ease-out
    state.container.y = 720 - (720 - CHYRON_Y) * eased;
  }

  // Scroll headline
  state.scrollX -= SCROLL_SPEED * dt;
  state.headlineText.position.x = state.scrollX;
  if (state.scrollX < -state.headlineText.width) {
    state.scrollX = HEADLINE_AREA_W;
  }
}
